### ISSUE TITLE
Problemas no aside de publicidade

### ISSUE THREAD

**Issue by esantelmo** [esantelmo/noticiasdomundo#17]
Prezados, fiz atualização do branch master hoje pela manhã. Infelizmente não foi possível fechar a primeira edição pois temos problemas no layout da publicidade.
Peço que verifiquem para podermos prosseguir. Farei uma nova tentativa hoje no fim do dia.
Sugiro formatar o aside de publicidade como flex com flow vertical e remover os divs e width 100%

**Comment by RodrigoTV8** [comment]
Ajuste realizado removendo classe que estava vinculada a publicidade.
